const words = {
  geral: [
    "sagaz", "âmago", "termo", "negro", "êxito", "mexer", "nobre", "senso", "afeto", "ética",
    "algoz", "plena", "fazer", "assim", "tênue", "mútua", "sobre", "aquém", "seção", "vigor",
    "poder", "sutil", "porém", "fosse", "cerne", "ideia", "sanar", "audaz", "moral", "inato",
    "quiçá", "desde", "muito", "justo", "sonho", "honra", "torpe", "razão", "amigo", "ícone",
    "égide", "etnia", "fútil", "anexo", "dengo", "tange", "haver", "lapso", "então", "expor",
    "tempo", "atriz", "boçal", "seara", "hábil", "saber", "mútuo", "casal", "graça", "xibiu",
    "óbice", "ávido", "dizer", "ardil", "pesar", "estar", "dever", "causa", "tenaz", "sendo",
    "ainda", "pária", "crivo", "brado", "temor", "coser", "genro", "comum", "ápice", "posse",
    "prole", "ânimo", "assaz", "ceder", "corja", "pauta", "detém", "fugaz", "censo", "ânsia",
    "culto", "atroz", "digno", "mundo", "forte", "mesmo", "vulgo", "vício", "gleba", "saúde",
    "criar", "cozer", "blues", "todos", "revés", "valha", "jeito", "pudor", "denso", "dogma",
    "neném", "louco", "atrás", "regra", "ordem", "limbo", "feliz", "pedir", "homem", "mercê",
    "clava", "impor", "ajuda", "usura", "banal", "round", "coisa", "juízo", "forma", "legal",
    "sábio", "falso", "certo", "falar", "servo", "prosa", "tenro", "pífio", "desse", "presa",
    "posso", "cunho", "herói", "devir", "viril", "vendo", "fácil", "ontem", "valor", "visar",
    "linda", "manso", "sério", "choro", "ébrio", "meiga", "puder", "mágoa", "acaso", "guisa",
    "fluir", "reaça", "ímpio", "afago", "lugar", "platô", "temer", "abrir", "garbo", "praxe",
    "união", "obter", "gerar", "burro", "matiz", "óbvio", "afins", "cisma", "bruma", "êxodo",
    "pleno", "crise", "vênia", "álibi", "tédio", "fluxo", "ritmo", "morte", "senil", "havia",
    "levar", "olhar", "enfim", "casta", "tomar", "visão", "gênio", "prumo", "ouvir", "parvo",
    "brega", "cabal", "reles", "falta", "menor", "vital", "parco", "calma", "bravo", "outro",
    "favor", "tecer", "pulha", "terra", "vivaz", "reter", "sábia", "ameno", "viver", "tendo",
    "único", "força", "laico", "valia", "passo", "grato", "achar", "noção", "nicho", "rever",
    "carma", "nossa", "possa", "papel", "ranço", "pobre", "rogar", "noite", "façam", "prime",
    "dúbio", "fardo", "farsa", "ativo", "coeso", "fator", "épico", "anelo", "claro", "óbito",
    "selar", "líder", "sesta", "leigo", "sinto", "porto", "citar", "cisão", "cesta", "ciúme",
    "vazio", "sonso", "deter", "atuar", "velho", "ficar", "gente", "tende", "haste", "adiar",
    "humor", "revel", "ideal", "fonte", "sulco", "ponto", "árduo", "labor", "igual", "marco",
    "senão", "remir", "terno", "exato", "feixe", "vemos", "amplo", "hiato", "tanto", "capaz",
    "lavra", "cauda", "débil", "relva", "ciclo", "inata", "tenra", "jovem", "ótica", "varão",
    "gesto", "chuva", "ambos", "raiva", "pouco", "coçar", "caçar", "toada", "sonsa", "vácuo",
    "velar", "apoio", "imune", "série", "vimos", "xeque", "algum", "farão", "feito", "horda",
    "fusão", "carro", "advém", "entre", "leito", "coesa", "probo", "minha", "sente", "cruel",
    "sorte", "trama", "doido", "frase", "anuir", "lazer", "brisa", "ímpar", "verso", "torço",
    "chata", "rigor", "massa", "botar", "prece", "blasé", "pegar", "maior", "dorso", "seita",
    "fauna", "moção", "signo", "furor", "áurea", "preso", "covil", "livro", "agora", "liame",
    "credo", "plano", "vetor", "comer", "flora", "casto", "saiba", "ocaso", "morar", "praia",
    "senda", "adeus", "pecha", "nunca", "dócil", "faina", "aliás", "peste", "houve", "árido",
    "setor", "ambas", "ardor", "manha", "mudar", "peixe", "parte", "rezar", "visse", "vírus",
    "antro", "risco", "meses", "salvo", "vulto", "junto", "pajem", "saída", "breve", "beata",
    "campo", "vasto", "ótimo", "aceso", "avaro", "grupo", "estão", "morro", "antes", "sinal",
    "reger", "banzo", "lenda", "andar", "conta", "áureo", "prado", "anais", "acima", "opção",
    "serão", "verbo", "oxalá", "festa", "segue", "fugir", "chulo", "vilão", "rapaz", "leite",
    "birra", "motim", "nação", "texto", "treta", "brava", "fruir", "índio", "tirar", "parar",
    "fitar", "átomo", "ídolo", "puxar", "jazia", "traga", "tenso", "reino", "gerir", "filho",
    "alude", "átrio", "prazo", "tosco", "prova", "turba", "norma", "bônus", "época", "exame",
    "manhã", "voraz", "corpo", "acesa", "sarça", "preto", "cheio", "bando", "malta", "aonde",
    "arcar", "ligar", "nosso", "fatos", "magia", "sinhá", "quase", "psico", "anciã", "venal",
    "cópia", "avião", "fatal", "certa", "longe", "logro", "dessa", "praga", "afora", "quota",
    "nível", "fixar", "oásis", "menta", "apego", "sexta", "mente", "messe", "pompa", "nódoa",
    "lidar", "perda", "apelo", "tocar", "coito", "alado", "parca", "jirau", "caixa", "sumir",
    "verve", "fraco", "glosa", "livre", "tinha", "soldo", "fotos", "vezes", "porta", "lindo",
    "firme", "grave", "cânon", "solto", "bater", "opaco", "faixa", "astro", "salve", "irmão",
    "sabia", "besta", "virão", "turva", "doído", "atual", "trupe", "fenda", "navio", "supra",
    "elite", "deixa", "grata", "pardo", "alçar", "exijo", "autor", "junco", "pique", "parva",
    "cioso", "curso", "viria", "bicho", "bioma", "macio", "douto", "desta", "pagão", "chato",
    "aluno", "reses", "ético", "cousa", "ficha", "calda", "menos", "posto", "abuso", "caber",
    "rádio", "vídeo", "locus", "supor", "culpa", "judeu", "lápis", "zelar", "verba", "super",
    "gosto", "drops", "suave", "calão", "retém", "extra", "advir", "agudo", "privê", "júlia",
    "molho", "torso", "baixo", "vosso", "piada", "facho", "peito", "vinha", "ígneo", "turma",
    "sítio", "passa", "pódio", "ruína", "asilo", "light", "combo", "traço", "órfão", "ávida",
    "estio", "pilar", "turvo", "louça", "chama", "ações", "mosto", "refém", "forem", "pisar",
    "páreo", "amena", "poeta", "mesma", "brabo", "museu", "acolá", "ereto", "finda", "lasso",
    "meigo", "local", "metiê", "optar", "medir", "drama", "busca", "teste", "poema", "tento",
    "surja", "autos", "facto", "cútis", "clima", "folga", "rumor", "coral", "aviso", "rouca",
    "geral", "cocho", "paira", "hobby", "amiga", "calmo", "pedra", "boato", "idoso", "tacha",
    "feroz", "urgia", "cetro", "volta", "rubro", "pacto", "feudo", "móvel", "lição", "crime",
    "monge", "açude", "golpe", "ateia", "clean", "daqui", "artur", "tetra", "ponha", "riste",
    "ecoar", "ébano", "carta", "corso", "casar", "bença", "natal", "manga", "monte", "falha",
    "saldo", "cacho", "aroma", "verde", "plumo", "vigia", "itens", "conto", "briga", "fazia",
    "vetar", "grama", "hoste", "escol", "tribo", "pasmo", "tarde", "fórum", "mangá", "letal",
    "amada", "única", "troça", "rival", "ornar", "pedro", "chefe", "vento", "súcia", "sósia",
    "civil", "fruto", "roupa", "úteis", "venha", "plaga", "penta", "nuvem", "pinho", "sarau",
    "tchau", "órgão", "plebe", "areia", "átimo", "swing", "jogar", "vazão", "cover", "cargo",
    "virar", "nesse", "lesse", "jejum", "berro", "arado", "stand", "macro", "seixo", "magna",
    "fosso", "axila", "finjo", "perto", "catre", "gíria", "rocha", "mídia", "farta", "beijo",
    "tiver", "varoa", "légua", "inter", "troca", "tutor", "tição", "bruto", "todas", "calor",
    "bruta", "traje", "deste", "renda", "close", "gabar", "pomar", "trato", "assar", "tenha",
    "porte", "surto", "guria", "perco", "amado", "vadio", "viram", "arfar", "nessa", "dança",
    "santo", "estro", "verão", "âmbar", "rural", "xucro", "feita", "nesta", "silvo", "odiar",
    "logos", "canso", "mamãe", "depor", "vista", "fossa", "laudo", "aviar", "bazar", "canto",
    "vedar", "marca", "grota", "chula", "etapa", "pavor", "recém", "negar", "cheia", "cenho",
    "salmo", "bolsa", "irado", "cerca", "cifra", "densa", "cinta", "minar", "ágape", "clero",
    "cinto", "visto", "ferpa", "régio", "coroa", "sofia", "bucho", "vagar", "burra", "horto",
    "urdir", "invés", "molde", "letra", "ruído", "largo", "segar", "folha", "lesão", "quais",
    "proto", "sótão", "paiol", "esgar", "jazer", "símio", "velha", "pugna", "final", "penso",
    "úbere", "trago", "morfo", "fundo", "lesto", "deram", "narco", "pasma", "vasta", "ceita",
    "queda", "podar", "crase", "linho", "olhos", "ufano", "álamo", "ardis", "troço", "linha",
    "piche", "troco", "apear", "viger", "úmido", "pólis", "frota", "preço", "folia", "bulir",
    "mocho", "neste", "áudio", "peita", "ileso", "outra", "farol", "resto", "disso", "monta",
    "manto", "matar", "cosmo", "redor", "chave", "seiva", "chaga", "barro", "cível", "bolso",
    "limpa", "limpo", "mover", "misto", "falsa", "retro", "lábia", "limpo", "vazia", "louca",
    "logia", "nácar", "veloz", "nariz", "campa", "justa", "barão", "bedel", "banto", "louro",
    "lutar", "álbum", "mimar", "macho", "sabor", "samba", "gemer", "dados", "punha", "axial",
    "toque", "lucro", "porca", "coevo", "arroz", "longo", "zumbi", "calça", "enjoo", "rente",
    "findo", "venho", "calvo", "salva", "subir", "farto", "urgir", "diabo", "pagar", "lousa",
    "baixa", "xampu", "pluma", "firma", "sacar", "valer", "solta", "sabiá", "ousar", "sexto",
    "bruxa", "forro", "torna", "fazes", "sigla", "fátuo", "repor", "reler", "choça", "lento",
    "fugiu", "gueto", "cardo", "hífen", "focar", "bugre", "pular", "demão", "corte", "canil",
    "corar", "vário", "custo", "feira", "voilà", "mania", "nesga", "versa", "míope", "rácio",
    "sadio", "ferir", "modal", "sócio", "harém", "tumba", "sugar", "tênis", "digna", "puído",
    "penca"
  ],
  verbs: [
    "ouvir", "viver", "morar", "jogar", "rever", "girar", "gerar", "tirar", "pegar", "calar",
    "haver", "expor", "mexer", "cozer", "criar"
  ],
  adjectives: [
    "sagaz", "âmago", "nobre", "plena", "sutil", "tênue", "mútua", "audaz", "moral", "fútil",
    "vigor", "digno", "forte", "justo", "feliz", "linda", "meiga", "plebe", "lindo", "denso",
    "fraco", "sábio", "falso", "pífio", "fácil", "pobre", "sério", "calmo", "manso", "amigo"
  ],
  reserve: [
    "carro", "livro", 
  ],
};

module.exports = words;